<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ja">
	<head>
		<title>Rust メモ: E0716 - 参照中の中間値の破棄</title>
		<link rel="stylesheet" href="style/base.css"/>
		<script src="../../lib/doc.js"></script>
		<script src="lib/base.js"></script>
	</head>
	<body>
		<header>
			<h1><script>Doc.insertTitle();</script></h1>
		</header>
<pre><samp class="console-rustc">
<mark class="error">error[E0716]</mark><mark class="title">: temporary value dropped while borrowed</mark>
</samp></pre>
		<p>
参照中に中間値が破棄された。
		</p>
		<section>
			<h1>パターン</h1>
			<nav class="sub"/>
			<section>
				<hgroup>
					<h1>パターン A</h1>
					<div class="subTitle">基本形</div>
				</hgroup>
				<p>
殆どの場合、式内の中間値の破棄は、文末 (セミコロンの位置) にて行われる。
				</p> <p>
そのため、それ以降にその中間値に由来する参照を使用するとエラーになる。
				</p>
				<section>
					<h2>サンプル</h2>
					<p>
以下では、式内の中間値 <code>Foo::new()</code> から、メソッド <code>val_ref()</code> で参照をたどり、その結果を変数 <code>ref_to_temp</code> へと保存して利用している。しかし、<code>ref_to_temp</code> へと値を保存する文の文末にてすでに参照先の中間値は破棄されてしまっている。
					</p>
<pre><code class="language-rust">
fn main() {
    let ref_to_temp = <mark class="error">Foo::new()</mark>.val_ref();
    println!("Value is {}.", *ref_to_temp);
}

struct Foo {
    val: i32
}

impl Foo {
    fn new() -&gt; Self {
        Self { val: 0 }
    }
    
    fn val_ref(&amp;self) -&gt; &amp;i32 {
        &amp;self.val
    }
}
</code></pre>
<pre><samp class="console-rustc">
<mark class="error">error[E0716]</mark><mark class="title">: temporary value dropped while borrowed</mark>
<mark class="info"> --&gt;</mark> src\main.rs:2:21
<mark class="info">  |</mark>
<mark class="info">2 |</mark>     let ref_to_temp = Foo::new().val_ref();
<mark class="info">  |</mark>                       <mark class="error">^^^^^^^^^^</mark>          <mark class="info">- temporary value is freed at the end of this statement</mark>
<mark class="info">  |</mark>                       <mark class="error">|</mark>
<mark class="info">  |</mark>                       <mark class="error">creates a temporary value which is freed while still in use</mark>
<mark class="info">3 |</mark>     println!("Value is {}.", *ref_to_temp);
<mark class="info">  |</mark>                              <mark class="info">------------ borrow later used here</mark>
<mark class="info">  |</mark>
<mark class="info">help</mark>: consider using a `let` binding to create a longer lived value
<mark class="info">  |</mark>
<mark class="info">2</mark> <mark class="edit">~</mark>     <mark class="edit">let binding = Foo::new();</mark>
<mark class="info">3</mark> <mark class="edit">~</mark>     let ref_to_temp = <mark class="edit">binding</mark>.val_ref();
</samp></pre>
				</section> <section>
					<h2>解決策</h2>
					<p>
エラーメッセージの <q>help</q> にある通り、中間値をローカル変数に保存する。
					</p>
					<aside class="normal">
						<p>
Rust の独特な仕様。
						</p> <p>
Rust 以外の多くの言語では、ローカル変数に計算過程の中間値を保存するかは、主にリファクタリングの話題である。ところが、Rust ではこれによりエラーの有無が変わる。
						</p> <p>
これと関連してか、他の言語では「変数を宣言する」や「変数を値で初期化する」などと表現するところを、Rust では「変数に値を束縛する (let binding)」などと表現する。
						</p>
					</aside>
				</section>
			</section> <section>
				<hgroup>
					<h1>パターン B</h1>
					<div class="subTitle">借用式</div>
				</hgroup>
				<p>
借用式 (<code>&amp;<var>x</var></code>) の演算対象 (<code><var>x</var></code>) がアドレスでなく通常の値の場合、必要に応じて現在のスコープに値が自動保存され、式の結果はそこへの参照となる。そのためこの場合、中間値を生成した文より後でも、スコープ内ならばその中間値への参照を使える。
				</p> <p>
つまり、借用式では中間値と参照まわりのエラーはあまり起きない。ただそれでも、中間値の参照を静的参照として利用したりすると、やはりエラーになる。
				</p>
				<section>
					<h2>サンプル</h2>
					<p>
以下では、借用式内の中間値 <code>Foo::new()</code> のフィールド <code>val</code> への参照が、変数 <code>ref_to_temp</code> から参照できるよう、中間値が自動保存されている。しかし、その中間値は静的に保存されているわけではない。そのため、<code>ref_to_temp</code> は、関数 <code>use_ref</code> の引数にはなれない。
					</p>
<pre><code class="language-rust">
fn main() {
    let ref_to_temp = &amp;<mark class="error">Foo::new()</mark>.val;
    use_ref(ref_to_temp);
}

fn use_ref(arg: &amp;'static i32) {
    println!("Value is {}.", *arg);
}

struct Foo {
    val: i32
}

impl Foo {
    fn new() -&gt; Self {
        Self { val: 0 }
    }
}
</code></pre>
<pre><samp class="console-rustc">
<mark class="error">error[E0716]</mark><mark class="title">: temporary value dropped while borrowed</mark>
<mark class="info"> --&gt;</mark> src\main.rs:2:24
<mark class="info">  |</mark>
<mark class="info">2 |</mark>     let ref_to_temp = &amp;Foo::new().val;
<mark class="info">  |</mark>                        <mark class="error">^^^^^^^^^^ creates a temporary value which is freed while still in use</mark>
<mark class="info">3 |</mark>     use_ref(ref_to_temp);
<mark class="info">  |</mark>     <mark class="info">-------------------- argument requires that borrow lasts for `'static`</mark>
<mark class="info">4 |</mark> }
<mark class="info">  |</mark> <mark class="info">- temporary value is freed at the end of this statement</mark>
</samp></pre>
				</section>
			</section>
		</section>
	</body>
</html>
